---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches: [master]
  merge_group:
    types: [checks_requested]
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  start:
    name: Start
    runs-on: ubuntu-24.04
    outputs:
      start: ${{ steps.merge-queue-ci-skipper.outputs.skip-check == 'false' }}
    steps:
      - name: Check If Starting
        id: merge-queue-ci-skipper
        uses: cariad-tech/merge-queue-ci-skipper@main

  flake:
    name: Check Flake
    needs: [start]
    if: needs.start.outputs.start == 'true'

    strategy:
      fail-fast: false
      matrix:
        os: [macos-26, macos-26-intel, ubuntu-24.04, ubuntu-24.04-arm]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Check
        run: nix flake check --impure

      - name: Format
        run: nix fmt -- --ci

      - name: Test
        run: nix develop .# --impure --command devenv test

  succeed:
    name: Succeed
    runs-on: ubuntu-24.04
    needs:
      - flake
    steps:
      - run: "true"
